version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0 # Use the Redis version you prefer
    container_name: redis-server
    ports:
      - "6379:6379" # Maps the Redis container port to your local machine
    restart: always
    volumes:
      - redis-data:/data # Persistent storage for Redis data
    command: [ "redis-server", "--appendonly", "yes" ] # Enable AOF for persistence

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://mongodb:27017/stagedb

volumes:
  redis-data:
    driver: local
  mongo-data: